# Generated by Django 5.2 on 2025-04-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
